"""Phase 4: Add Prescription, PrescriptionItem, and MedicalReport models

Revision ID: 75edb3c8d629
Revises: 9dc1265569fe
Create Date: 2026-09-12 14:37:30.898594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75edb3c8d629'
down_revision = '9dc1265569fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reports_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))

    op.drop_table('prescription_items')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_appointment_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_appointment_id'))

    op.drop_table('medical_reports')
    # ### end Alembic commands ###
