"""Add CheckConstraints for role and verification status

Revision ID: a6b78cbdba38
Revises: 61cb178f911a
Create Date: 2026-08-15 23:45:41.181168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b78cbdba38'
down_revision = '61cb178f911a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_doctors_verification_status', "verification_status IN ('pending', 'approved', 'rejected')")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_users_role', "role IN ('patient', 'doctor', 'admin')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role', type_='check')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint('ck_doctors_verification_status', type_='check')

    # ### end Alembic commands ###
